#!/usr/bin/env bash

set -eo pipefail

export THIS_DIR="$(cd "$(dirname $(dirname $0))"; pwd)"
cd "${THIS_DIR}"

source test/config.sh
source test/lib.sh

log-lifecycle Building helm

# make helm so we can use it to test changed charts
# make build test

run-test-plan
