site_name: Helm Documentation
pages:
 - Home: index.md
 - Architecture: architecture.md
 - Using Labels: using_labels.md
 - Modeling Services: modeling_services.md
 - Workspace Layout: workspace.md
 - Authoring Charts: authoring_charts.md
theme: readthedocs
